### ISSUE TITLE
(FeatureRequest) Funktionen und Räume ausblenden

### ISSUE THREAD

**Issue by sigi2345** [nisiode/ioBroker.iogopro#1]
Hallo,

bitte Funktionen und Räume ausblendbar machen.

Danke 
Sigi234

**Comment by nisiode** [comment]
Ich schlage vor eine globale Blacklist in der Instanz Konfig. Gibt es bereits Adapter mit einem ähnlichen Feature in der Konfiguration der Instanz?

**Comment by sigi2345** [comment]
> Ich schlage vor eine globale Blacklist in der Instanz Konfig. Gibt es bereits Adapter mit einem ähnlichen Feature in der Konfiguration der Instanz?

https://github.com/afuerhoff/ioBroker.fb-checkpresence

**Comment by nisiode** [comment]
Feature ist umgesetzt in v0.2.0
