### ISSUE TITLE
Adapter lässt sich nicht installieren

### ISSUE THREAD

**Issue by walterwwolfde** [nisiode/ioBroker.iogopro#10]
$ iobroker add iogopro --host f7a7c72046b2

NPM version: 6.14.15npm install iobroker.iogopro@0.2.2 --loglevel error --prefix "/opt/iobroker" (System call)

npm ERR! Unexpected end of JSON input while parsing near '...Hegl5w==","shasum":"1'

npm ERR! A complete log of this run can be found in:

npm ERR! /opt/iobroker/.npm/_logs/2021-11-17T08_32_28_128Z-debug.log

host.f7a7c72046b2 Cannot install iobroker.iogopro@0.2.2: 1

ERROR: Process exited with code 25

**Comment by walterwwolfde** [comment]
Auch mit der Version 0.2.5 nicht


72 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...Hegl5w==","shasum":"1'
72 verbose stack     at JSON.parse (<anonymous>)
72 verbose stack     at parseJson (/usr/lib/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
72 verbose stack     at /usr/lib/node_modules/npm/node_modules/node-fetch-npm/src/body.js:96:50
72 verbose stack     at runMicrotasks (<anonymous>)
72 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)
73 verbose cwd /opt/iobroker
74 verbose Linux 5.10.63-v7l+
75 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "nisiode/ioBroker.iogopro" "--prefix" "/opt/iobroker"
76 verbose node v12.22.7
77 verbose npm  v6.14.15
78 error Unexpected end of JSON input while parsing near '...Hegl5w==","shasum":"1'
79 verbose exit [ 1, true ]

**Comment by nisiode** [comment]
Installation ist getestet und ohne Fehler: https://github.com/nisiode/ioBroker.iogopro/runs/4026707762?check_suite_focus=true

Scheint aber nicht selten zu sein laut Google und manchmal hilft dann ein: "npm cache clean --force"

**Comment by walterwwolfde** [comment]
Es liegt wohl an dem npm Paket firebase ... das lässt sich manuell auch nicht installieren

**Comment by nisiode** [comment]
Hat das "npm cache clean --force" geholfen?

**Comment by walterwwolfde** [comment]
Nein, leider nicht

**Comment by nisiode** [comment]
Dann mal zusätzlich noch bereits vorhandene Ordner ioBroker.iogo und ioBroker.iogopro löschen

**Comment by walterwwolfde** [comment]
Ich konnte firebase in der Version 8.10 manuell installieren, dann hat auch die Installation des iogo Adapters geklappt. 
Vielen Dank für die Hilfe
