### ISSUE TITLE
feature request: Datenpunkte zusammenfügen

### ISSUE THREAD

**Issue by santa81** [nisiode/ioBroker.iogopro#4]
derzeit haben dimmbare Lampen 2 Datenpunkte, 1 für an/aus und 1 für Helligkeit.
cool wäre es wenn diese beiden zusammengefügt werden könnten.
Also zum wenn lampexy und lampexy.brightness vorhanden, dann zeige die beiden in einer Zeile in  der app an

**Comment by santa81** [comment]
Vielleicht lässt sich das auch darüber lösen, das man doch enums als channel in bestimmten Fällen in iogopro zulässt.
Das heißt, ist zum Beispiel ein enum mit einem Channel einer Lampe zugeordnet, dann wird geschaut ob darin die roles 
switch.light
level.brightness
usw. vorhanden sind. Sind diese eben vorhanden kann man über das icon die lampe anschalten und über den schieberegler dimmen. Sollten noch mehr gültige Optionen vorhanden sein, erscheinen diese wenn man auf das ganze klickt.

Eventuell finden sich anschließend noch andere Anwendungsfälle.

**Comment by nisiode** [comment]
ioBroker stellt aktuell keine Gruppierung von States zu Geräten bereit.
Aktuell wird das Thema hier z.B. diskutiert: https://forum.iobroker.net/topic/35020/devices-alias-assistenten-visualisierungen-die-zukunft
