### ISSUE TITLE
Standard Icons im Darkmode nicht gut zu erkennen

### ISSUE THREAD

**Issue by braindead1** [nisiode/ioBroker.iogopro#9]
Die Standard Icons, die man im iobroker Räumen und Funktionen zuordnen kann, sind im Darkmode nicht gut zu erkennen.

![Screenshot_20211101_131620.jpg](https://user-images.githubusercontent.com/2136249/139670028-cea7ce82-2e8e-450e-9202-1d4fa8029dde.jpg)

**Comment by santa81** [comment]
Ich finde es gerade gut weil nicht aufdringlich, aber Geschmäcker sind verschieden. Vielleicht hat nis aber auch eine Idee uns alle glücklich zu machen.

**Comment by braindead1** [comment]
Graue Icons würden sehr gut zum Rest passen.

**Comment by nisiode** [comment]
Ich kann die Icons nicht pauschal umfärben, damit würden auf individuelle Icons betroffen.
